/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function aFunction(aArg: number): number
export function coolFunction(aArg: number): number
export function getUndefined(): void
export function getNull(): null
export function getEnv(env: string): string | null
export function sum(a: number, b: number): number
export function isGood(): boolean
export function getBufferSum(buf: Buffer): number
export function readBuffer(file: string): Buffer
export function keys(obj: object): Array<string>
export function logStringField(obj: object, field: string): void
export function createObj(): object
export const DEFAULT_CONST: number
export const enum Kind {
  Dog = 0,
  Cat = 1,
  Duck = 2
}
export class Animal {
  name: string
  kind: number
  constructor(name: string, kind: number)
  changeName(newName: string): void
}
